//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrayerTiming
    {
        public int Id { get; set; }
        public int MasjidId { get; set; }
        public System.TimeSpan Fajar { get; set; }
        public System.TimeSpan Zohar { get; set; }
        public System.TimeSpan Asar { get; set; }
        public System.TimeSpan Magrib { get; set; }
        public System.TimeSpan Isha { get; set; }
        public System.TimeSpan Juma { get; set; }
        public System.DateTime Date { get; set; }
    }
}
